---
title: "Cellular, nuclear, and DenoIST expression and annotations"
author: "heinin"
date: "2025-09-16"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

### Packages and environment variables

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(arrow)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(ggrastr)
  library(googlesheets4)
  library(workflowr)})

```

### Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/PIPAC_spatial/")
set.seed(9999)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

source("/home/hnatri/PIPAC_spatial/code/PIPAC_colors_themes.R")
source("/home/hnatri/PIPAC_spatial/code/plot_functions.R")

```

### Import data

```{r, message = F, warning = F, fig.width = 6, fig.height = 4}

#nucl_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/PIPAC_NC50_NN20_PC20_Seurat_annotated_metadata.rds")

# Before splitting immune and nonimmune and reclustering
cell_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/cell_merged_spatial_filtered_splitsamples_clustered_NN30_PC50_Seurat_denoIST.rds")

# Normalizing and scaling all assays
DefaultAssay(cell_data) <- "RNA"
cell_data <- cell_data %>%
  JoinLayers() %>%
  NormalizeData() %>%
  ScaleData()

DefaultAssay(cell_data) <- "nucleus_RNA"
cell_data <- cell_data %>%
  JoinLayers() %>%
  NormalizeData() %>%
  ScaleData()

DefaultAssay(cell_data) <- "denoist_RNA"
cell_data <- cell_data %>%
  JoinLayers() %>%
  NormalizeData() %>%
  ScaleData()

```

### Plotting expression of all genes

```{r, message = F, warning = F, fig.width = 12, fig.height = 4}

# Only looking at one sample
seurat_data_subset <- subset(cell_data,
                             subset = Sample == "S21-24369_2A")

# Cellular
cell_exp <- LayerData(seurat_data_subset,
                      assay = "RNA",
                      layer = "data")

cell_exp <- as.data.frame(cell_exp) %>%
  rownames_to_column(var = "gene") %>%
  #t() %>%
  as_tibble() %>%
  pivot_longer(cols = colnames(cell_exp), names_to = "cell", values_to = "exp")

# Nuclear
nucl_exp <- LayerData(seurat_data_subset,
                      assay = "nucleus_RNA",
                      layer = "data")

nucl_exp <- as.data.frame(nucl_exp) %>%
  rownames_to_column(var = "gene") %>%
  #t() %>%
  as_tibble() %>%
  pivot_longer(cols = colnames(nucl_exp), names_to = "cell", values_to = "exp")

# DenoIST
denoist_exp <- LayerData(seurat_data_subset,
                         assay = "denoist_RNA",
                         layer = "data")

denoist_exp <- as.data.frame(denoist_exp) %>%
  rownames_to_column(var = "gene") %>%
  #t() %>%
  as_tibble() %>%
  pivot_longer(cols = colnames(denoist_exp), names_to = "cell", values_to = "exp")

#identical(rownames(cell_exp), rownames(nucl_exp))

# Merging
merged_exp <- cbind(cell_exp, nucl_exp, denoist_exp)
colnames(merged_exp) <- c("gene1", "cell1", "cell_exp", "gene2", "cell2", "nucl_exp", "gene3", "cell3", "denoist_exp")

#identical(merged_exp$cell1, merged_exp$cell2)
#identical(merged_exp$gene1, merged_exp$gene2)

merged_exp <- merged_exp[,c(1, 2, 3, 6, 9)]

p1 <- merged_exp %>%
  ggplot(aes(x = cell_exp, y = nucl_exp)) +
  #geom_pointdensity() +
  geom_point(alpha = 0.2) +
  #stat_summary(fun.data = mean_cl_normal) + 
  geom_smooth(method='lm', formula= y~x) +
  theme_classic() +
  ylab("Nuclear transcripts") +
  xlab("All transcripts")

p1 <- rasterize(p1, layers='Point', dpi = 300)

p2 <- merged_exp %>%
  ggplot(aes(x = cell_exp, y = denoist_exp)) +
  #geom_pointdensity() +
  geom_point(alpha = 0.2) +
  #stat_summary(fun.data = mean_cl_normal) + 
  geom_smooth(method='lm', formula= y~x) +
  theme_classic() +
  ylab("DenoIST transcripts") +
  xlab("All transcripts")

p2 <- rasterize(p2, layers='Point', dpi = 300)

p3 <- merged_exp %>%
  ggplot(aes(x = denoist_exp, y = nucl_exp)) +
  #geom_pointdensity() +
  geom_point(alpha = 0.2) +
  #stat_summary(fun.data = mean_cl_normal) + 
  geom_smooth(method='lm', formula= y~x) +
  theme_classic() +
  ylab("Nuclear transcripts") +
  xlab("DenoIST transcripts")

p3 <- rasterize(p3, layers='Point', dpi = 300)

patchwork::wrap_plots(p1, p2, p3, ncol = 3)

```

### Marker information

```{r, message = F, warning = F, fig.width = 6, fig.height = 4}

gs4_deauth()
metadata  <- gs4_get("https://docs.google.com/spreadsheets/d/1sXXwOreLxjMSUoPt79c6jmaQpluWkaxA5P5HfDsed3I/edit?usp=sharing")
markers <- read_sheet(metadata, sheet = "Markers")
first_pass_annot <- read_sheet(metadata, sheet = "Main cluster annotations")

```

### Cluster overlap

```{r, message = F, warning = F, fig.width = 10, fig.height = 6}

create_barplot(cell_data,
               group_var = "leiden_0.5",
               plot_var = "Annotation",
               plot_levels = sort(unique(cell_data$Annotation)),
               group_levels = sort(unique(cell_data$leiden_0.5)),
               plot_colors = pipac_celltype_col,
               var_names =  c("Frequency", ""),
               legend_title = "")

plot_clusters <- as.factor(c(0, seq(1:19)))

plot_clusters_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(plot_clusters))
names(plot_clusters_col) <- levels(plot_clusters)

create_barplot(cell_data,
               plot_var = "leiden_0.5",
               group_var = "Annotation",
               group_levels = sort(unique((cell_data$Annotation))),
               plot_levels = sort(unique(cell_data$leiden_0.5)),
               plot_colors = plot_clusters_col,
               var_names =  c("Frequency", ""),
               legend_title = "")

```

### Feature expression

```{r, message = F, warning = F, fig.width = 10, fig.height = 6, eval = F}

plot_features <- c("PTPRC",
                   "CD3D", "CD3E", "CD4", "CD8A", # T cells
                   "STAT4", "STAT3", "TIGIT", "GZMB",
                   "SELL", "CD19", # B cells
                   "CD68", "CD44", "MARCO", "APOE", # Macrophages
                   "C1QB", "C1QBP",
                   "MUC5AC", "NOTCH3", "MS4A1", "PGA5", # Lineage markers
                   "FN1", "DCN", "LUM", # Fibroblasts
                   "EGR3", "TP53", "JUN", "KIT", # Tumor
                   "SOX9", "RNF43", "EPCAM")

DotPlot(cell_data,
        group.by = "Annotation",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "nucleus_RNA") +
  RotatedAxis() +
  ggtitle("Nuclear transcripts, by original annotation")

DotPlot(cell_data,
        group.by = "Annotation",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "RNA") +
  RotatedAxis() +
  ggtitle("All transcripts, by original annotation")

DotPlot(cell_data,
        group.by = "Annotation",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "denoist_RNA") +
  RotatedAxis() +
  ggtitle("DenoIST transcripts, by original annotation")

DotPlot(cell_data,
        group.by = "leiden_0.5",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "nucleus_RNA") +
  RotatedAxis() +
  ggtitle("Nuclear transcripts, by cell-based cluster")

DotPlot(cell_data,
        group.by = "leiden_0.5",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "RNA") +
  RotatedAxis() +
  ggtitle("All transcripts, by cell-based cluster")

DotPlot(cell_data,
        group.by = "leiden_0.5",
        features = plot_features,
        cols = c("gray89", "tomato3"),
        assay = "denoist_RNA") +
  RotatedAxis() +
  ggtitle("DenoIST transcripts, by cell-based cluster")

# Rscript -e "rmarkdown::render('compare_cellular_nuclear_denoist_annot.Rmd')"
# Then "mv *.html /home/hnatri/PIPAC_spatial/docs/"


```


