---
title: "PIPAC Xenium data analysis"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

### Analyzing the PIPAC peritoneal tumor/normal Xenium data

Project spreadsheets in [Google Sheets](https://docs.google.com/spreadsheets/d/1sXXwOreLxjMSUoPt79c6jmaQpluWkaxA5P5HfDsed3I/edit?usp=sharing).

Processing and annotation\
1. [Data processing](Xenium_processing.html)\
1.2 [Compare nuclear, cellular, and denoised transcript counts](compare_cellular_nuclear_denoist_annot.html)\
2. [Splitting sampes on TMAs](splitting_samples.html)\
3. Clustering using the rapids pipeline (/code/rapids_pipeline)\
4. [Post-clustering visualization](post_clustering.html)\
5. [1st pass annotation (nuclear transcripts)](annotation.html)\
5. [1st pass annotation (DenoIST transcripts)](annotation_cell.html)\
6. Reclustering immune and non-immune subsets using rapids\
7. [Immune cell annotation (nuclear transcripts)](immune_annotation.html)\
8. [Non-immune annotation (nuclear transcripts)](nonimmune_annotation.html)\
9. [2nd pass annotation (nuclear transcripts)](annotation_2nd_pass.html)\
10. [Adding patient metadata](add_metadata.html)\
13. [Feature expression by cell type](feature_expression.html)\

Visualization\
1. [Plotting by group](plot_by_group.html)\

Niche and proximity analysis\
1. [Niche construction](niche_construction.html)\
2. [Proximity](proximity.html)\

Arm 3 analysis\
1. [Arm 3 first-pass comparative analysis](arm3_comparative_analysis.html)\
2. [CAF analysis](CAF_analysis.html)\
3. [Immune analysis](immune_analysis.html)\

CAFs\
1. [CAF bulk-RNAseq with and without Mitomycin C](CAF_bulkRNAseq.html)\
2. [CT26 + CAF scRNAseq processing](PDX_CAF_scRNAseq_processing.html)\
3. [CT26 + CAF scRNAseq integration and 1st pass annotation](PDX_CAF_scRNAseq_analysis.html)\
4. [CT26 + CAF scRNAseq subclustering and 2nd pass annotation](PDX_CAF_subclustering.html)\
5. [CT26 + CAF scRNAseq comparative analysis](PDX_CAF_scRNAseq_comparative_analysis.html)\
6. [CT26 + CAF scRNAseq CMS scoring](PDX_CAF_scRNAseq_CMS.html)\

Contact: Heini M Natri, hnatri@tgen.org
