---
title: "Analysis of the non-immune fraction of PDX CAF scRNAseq"
author: "heinin"
date: "2026-01-31"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

## Libraries and environment variables

```{r, message = F, warning = F}

library(workflowr)
library(Seurat)
library(googlesheets4)
library(tidyverse)
library(plyr)
library(SoupX)
library(scProportionTest)
library(clusterProfiler)
library(org.Hs.eg.db)
library(org.Mm.eg.db)
library(biomaRt)
library(gprofiler2)

setwd("/home/hnatri/PIPAC_spatial/")
set.seed(1234)
options(future.globals.maxSize = 30000 * 1024^2)
reduction <- "umap"

source("/home/hnatri/SingleCellBestPractices/scripts/preprocessing_qc_module.R")
source("/home/hnatri/SingleCellBestPractices/scripts/integration_module.R")
source("/home/hnatri/Utilities/utilities.R")
source("/home/hnatri/PIPAC_spatial/code/PIPAC_colors_themes.R")
source("/home/hnatri/PIPAC_spatial/code/plot_functions.R")

# Markers
main_plot_features <- c("PTPRC", "CD3D", "CD3E", "CD4", "CD8A", "JAK1", "JAK2", "STAT4", "STAT3", "TIGIT", "GZMB", "SELL", "CD19", "CD68", "CD44", "MARCO", "APOE", "C1QB", "C1QBP", "CD163", "SPP1", "VCAN", "MUC5AC", "NOTCH3", "RGS5", "MS4A1", "PGA5", "PLVAP", "CCL21", "LYVE", "SPARCL1", "FN1", "DCN", "LUM", "COL1A2", "PDPN", "ACTA2", "LMNA", "EGR3", "TP53", "JUN", "FOS", "BRAF", "KIT", "SOX9", "RNF43", "EPCAM", "PECAM", "CEACAM", "TGFB1", "JUNB", "TCF7", "GZMA", "GZMK", "CD47", "CD74", "LYZ", "TREM2", "CD247", "COL5A1", "SPARC", "CD36", "CTLA4", "RGS1", "CCL2", "SELENOP", "LYVE1", "CTSD", "MMP9", "CDK1", "FLT1", "RAMP2", "CCL14", "MCAM", "NRP1", "CEACAM6", "IL32", "TGFBI", "VEGFA", "LAMP1", "IGFBP7", "POSTN", "C1S", "C1R", "CSF1", "NOTCH1", "FOXP3", "IL2RB", "TUBA1B", "S100A9", "C3", "CXCR2", "SDC1", "CD38", "IGHG1", "PRDX4", "ICAM1", "GATA2", "CXCL3")

mycafs <- c("TGFB1", "ACTA2", "TAGLN") #"HOPX", "MYL9"
icafs <- c("IL6", "CXCL12", "CXCL14") #"CXCL13", 
abcafs <- c("CD74", "HLA-DPB1", "HLA-DPB2", "HLA-DQA1", "HLA-DRA", "HLA-DRB1")
ficafs <- c("SFRP2", "SFRP4", "COMP", "CXCL14", "PLA2G2A", "ASPN")

main_plot_features <- c(main_plot_features, mycafs, icafs, abcafs, ficafs)
main_plot_features <- unique(main_plot_features)

main_plot_features <- gorth(main_plot_features, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name

```

## Import integrated data

```{r, message = F, warning = F, eval = T, eval = F}

seurat_data <- readRDS("/tgen_labs/banovich/PIPAC/CAF_scRNAseq/PDX_CAF_Seurat_integrated.rds")

annotations <- data.frame("cluster" = c(0, seq(1, 24)),
                          "annotation" = c("Tumor1", # 0
                                           "Proliferating1",
                                           "Tumor2",
                                           "CAF1", # 3
                                           "Tumor3", # 4
                                           "CAF2",
                                           "Proliferating2",
                                           "Tumor4",
                                           "CAF3", #8
                                           "CAF4",
                                           "Myeloid1",
                                           "Myeloid2",
                                           "Lymphoid1", # 12
                                           "Lymphoid2",
                                           "CAF5",
                                           "CAF6", # 15
                                           "CAF7",
                                           "Immune_Unclassified1",
                                           "Tumor5",
                                           "Proliferating3",
                                           "Immune_Unclassified2",
                                           "Immune_Unclassified3",
                                           "Immune_Unclassified4",
                                           "Immune_Unclassified5",
                                           "Immune_Unclassified6"))
seurat_data$Annotation <- mapvalues(seurat_data$harmony_snn_res.0.8,
                                    from = annotations$cluster,
                                    to = annotations$annotation)

table(seurat_data$Sample)
table(seurat_data$Annotation)

# Fixing mt and rb scores
#seurat_data <- PercentageFeatureSet(seurat_data, pattern = "^mt-", col.name = "percent.mt_RNA", assay = "RNA")
#seurat_data <- PercentageFeatureSet(seurat_data, pattern = "^Rp[SL]|^MRp[SL]", col.name = "percent.ribo_RNA", assay = "RNA")
#seurat_data <- PercentageFeatureSet(seurat_data, pattern = "mt-", col.name = "percent.mt_SoupX_RNA", assay = "SoupX_RNA")
#seurat_data <- PercentageFeatureSet(seurat_data, pattern = "^Rp[SL]|^MRp[SL]", col.name = "percent.ribo_SoupX_RNA", assay = "SoupX_RNA")

# saveRDS(seurat_data, "/tgen_labs/banovich/PIPAC/CAF_scRNAseq/PDX_CAF_Seurat_integrated_annotated.rds")

```

## Subset non-immune cells and re-integrate

```{r, message = F, warning = F, eval = F}

nonimmune <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 14, 15, 16, 18, 19)
seurat_data <- subset(seurat_data, subset = harmony_snn_res.0.8 %in% nonimmune)

table(seurat_data$harmony_snn_res.0.8)
table(seurat_data$Annotation)
seurat_data$Annotation <- factor(seurat_data$Annotation, levels = sort(unique(seurat_data$Annotation)))

# Splitting layers
#seurat_data[["RNA"]] <- split(seurat_data[["RNA"]], f = seurat_data$Sample)

DefaultAssay(seurat_data) <- "RNA"
seurat_data <-  SCTransform(seurat_data, 
                            vars.to.regress = c("percent.mt_RNA", "nCount_RNA", "nFeature_RNA"),
                            verbose = F)

s.genes <- cc.genes.updated.2019$s.genes
g2m.genes <- cc.genes.updated.2019$g2m.genes

mmus_s <- gorth(s.genes, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name
mmus_g2m <- gorth(g2m.genes, source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name

seurat_data <- CellCycleScoring(seurat_data,
                                s.features = mmus_s,
                                g2m.features = mmus_g2m,
                                set.ident = F,
                                verbose = F) 

seurat_data <-  SCTransform(seurat_data, 
                            vars.to.regress = c("S.Score", "G2M.Score", "Phase"),
                            verbose = F)

seurat_data <- RunPCA(seurat_data, assay = "SCT",
                      verbose = F)

seurat_integrated <- IntegrateLayers(object = seurat_data,
                                     method = HarmonyIntegration,
                                     orig.reduction = "pca",
                                     new.reduction = 'harmony',
                                     normalization.method = "SCT",
                                     k.weight = 20,
                                     verbose = FALSE)

#saveRDS(seurat_integrated, "/scratch/hnatri/PIPAC/PDX_CAF_nonimmune.rds")

```

## Dimensionality reduction and clustering

```{r, message = F, warning = F, fig.width = 5, fig.height = 4, eval = F}

seurat_integrated <- readRDS("/scratch/hnatri/PIPAC/PDX_CAF_nonimmune.rds")

seurat_integrated <-  SCTransform(seurat_integrated, 
                                  vars.to.regress = c("S.Score", "G2M.Score", "Phase"),
                                  verbose = F)

seurat_integrated <- RunPCA(seurat_integrated,
                            assay = "SCT",
                            verbose = F)

umap_pcs <- get_pcs(seurat_integrated, reduction_name = "pca")

seurat_integrated <- RunUMAP(object = seurat_integrated,
                             assay = "SCT",
                             reduction = "harmony",
                             reduction.name = "harmony_umap",
                             reduction.key = "harmony_umap_",
                             dims = 1:min(umap_pcs),
                             return.model = TRUE,
                             verbose = F)

seurat_integrated <- FindNeighbors(object = seurat_integrated,
                                 assay = "SCT",
                                 reduction = "harmony",
                                 dims = 1:min(umap_pcs),
                                 graph.name = c("harmony_nn",
                                                "harmony_snn"),
                                 verbose = F)

seurat_integrated <- FindClusters(object = seurat_integrated,
                                resolution = c(0.1,0.2,0.3,0.5,0.8,1),
                                graph.name = "harmony_snn",
                                 verbose = F)

DimPlot(seurat_integrated,
        group.by = "harmony_snn_res.0.8",
        reduction = "harmony_umap",
        label = T) +
  coord_fixed(ratio = 1) +
  theme_bw() +
  NoLegend()

table(seurat_integrated$harmony_snn_res.0.8)

#saveRDS(seurat_integrated, "/scratch/hnatri/PIPAC/PDX_CAF_nonimmune.rds")

```

## Annotation

SoupX RNA

```{r, message = F, warning = F, fig.width = 22, fig.height = 56, eval = F}

seurat_integrated <- readRDS("/scratch/hnatri/PIPAC/PDX_CAF_nonimmune.rds")

DefaultAssay(seurat_integrated) <- "SoupX_RNA"
seurat_integrated <- JoinLayers(seurat_integrated)
seurat_integrated <- NormalizeData(seurat_integrated)

FeaturePlot(seurat_integrated,
            features = main_plot_features,
            cols = c("gray98", "tomato3"),
            reduction = "harmony_umap",
            raster = T,
            order = T,
            ncol = 5) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()

```

RNA

```{r, message = F, warning = F, fig.width = 4, fig.height = 4}

seurat_integrated <- readRDS("/scratch/hnatri/PIPAC/PDX_CAF_nonimmune.rds")

DefaultAssay(seurat_integrated) <- "RNA"
seurat_integrated <- JoinLayers(seurat_integrated)
seurat_integrated <- NormalizeData(seurat_integrated)

DimPlot(seurat_integrated,
        group.by = "harmony_snn_res.0.8",
        reduction = "harmony_umap",
        label = T) +
  coord_fixed(ratio = 1) +
  theme_bw() +
  NoLegend()

table(seurat_integrated$harmony_snn_res.0.8)

```

```{r, message = F, warning = F, fig.width = 22, fig.height = 56}

FeaturePlot(seurat_integrated,
            features = main_plot_features,
            cols = c("gray98", "tomato3"),
            reduction = "harmony_umap",
            raster = T,
            order = T,
            ncol = 5) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()

```

```{r, message = F, warning = F, fig.width = 12, fig.height = 8}

mini_features <- gorth(c("CD3E", "CD8", "SPP1", "CD68",
                         "FN", "COL1A1", "EPCAM"), source_organism = "hsapiens", target_organism = "mmusculus")$ortholog_name

FeaturePlot(seurat_integrated,
            features = mini_features,
            cols = c("gray98", "tomato3"),
            reduction = "harmony_umap",
            raster = T,
            order = T,
            ncol = 3) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()

```

```{r, message = F, warning = F, fig.width = 8, fig.height = 16}

clusters <- as.factor(sort(unique(seurat_integrated$harmony_snn_res.0.8)))
cluster_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(clusters))
names(cluster_col) <- levels(clusters)

create_dotplot_heatmap(seurat_object = seurat_integrated,
                       plot_features = main_plot_features,
                       group_var = "harmony_snn_res.0.8",
                       group_colors = cluster_col,
                       column_title = "",
                       row_km = 5,
                       col_km = 5,
                       row.order = NULL,
                       col.order = NULL)

```

### Top cluster markers

```{r, message = F, warning = F, fig.width = 5, fig.height = 4}

Idents(seurat_integrated) <- seurat_integrated$harmony_snn_res.0.8
cluster_markers <- FindAllMarkers(seurat_integrated,
                                  return.thresh = 0.01,
                                  logfc.threshold = 0.5,
                                  min.pct = 0.20,
                                  verbose = F)

table(cluster_markers$cluster)

top_cluster_markers <- cluster_markers %>%
  arrange(dplyr::desc(avg_log2FC)) %>%
  group_by(cluster) %>%
  dplyr::slice(1:10)

top_cluster_markers_save <- cluster_markers %>%
  arrange(dplyr::desc(avg_log2FC)) %>%
  group_by(cluster) %>%
  dplyr::slice(1:30)

write.table(top_cluster_markers_save, "/home/hnatri/PIPAC_spatial/PDX_CAF_nonimmune_cluster_markers.tsv",
            quote = F, sep = "\t")

```


```{r, message = F, warning = F, fig.width = 8, fig.height = 21}

create_dotplot_heatmap(seurat_object = seurat_integrated,
                       plot_features = unique(top_cluster_markers$gene),
                       group_var = "harmony_snn_res.0.8",
                       group_colors = cluster_col,
                       column_title = "",
                       row_km = 5,
                       col_km = 5,
                       row.order = NULL,
                       col.order = NULL)

```

```{r, message = F, warning = F, fig.width = 22, fig.height = 66}

FeaturePlot(seurat_integrated,
            features = unique(top_cluster_markers$gene),
            cols = c("gray98", "tomato3"),
            reduction = "harmony_umap",
            raster = T,
            order = T,
            ncol = 8) &
  coord_fixed(ratio = 1) &
  theme_bw() &
  NoLegend()ß

```

### QC metrics by cluster

```{r, message = F, warning = F, fig.width = 12, fig.height = 9}

VlnPlot(seurat_integrated,
        features = c("nCount_RNA", "nFeature_RNA", "percent.mt_RNA"),
        group.by = "harmony_snn_res.0.8",
        cols = cluster_col,
        pt.size = 0,
        ncol = 1) &
  NoLegend()

```

### Adding annotations

```{r, message = F, warning = F, fig.width = 12, fig.height = 8, eval = F}

# Annotation df
# Non-immune c(0, 1, 2, 3, 4, 7, 9, 11, 12)
annotations <- data.frame("cluster" = c(0, seq(1, 24)),
                          "annotation" = c("Tumor1", # 0
                                           "Proliferating1",
                                           "Tumor2",
                                           "CAF1", # 3
                                           "Tumor3", # 4
                                           "CAF2",
                                           "Proliferating2",
                                           "Tumor4",
                                           "CAF3", #8
                                           "CAF4",
                                           "Myeloid1",
                                           "Myeloid2",
                                           "Lymphoid1", # 12
                                           "Lymphoid2",
                                           "CAF5",
                                           "CAF6", # 15
                                           "CAF7",
                                           "Immune_Unclassified1",
                                           "Tumor5",
                                           "Proliferating3",
                                           "Immune_Unclassified2",
                                           "Immune_Unclassified3",
                                           "Immune_Unclassified4",
                                           "Immune_Unclassified5",
                                           "Immune_Unclassified6"))
seurat_integrated$Annotation <- mapvalues(seurat_integrated$harmony_snn_res.0.8,
                                from = annotations$cluster,
                                to = annotations$annotation)

```

## Comparative analysis

### Cell type proportions

```{r, message = F, warning = F, fig.width = 7, fig.height = 5, eval = F}

table(seurat_integrated$Sample)
table(seurat_integrated$Sample, seurat_integrated$Annotation)

cts <- as.factor(sort(unique(as.character(seurat_integrated$Annotation))))
ct_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(cts))
names(ct_col) <- levels(cts)

create_barplot(seurat_integrated,
               group_var = "Sample",
               plot_var = "Annotation",
               plot_levels = sort(unique(as.character(seurat_integrated$Annotation))),
               group_levels = sort(unique(seurat_integrated$Sample)),
               plot_colors = ct_col,
               var_names =  c("Frequency (%)", ""),
               legend_title = "Celltype")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 6, eval = F}

prop_test <- sc_utils(seurat_integrated)
prop_test <- permutation_test(
	prop_test, cluster_identity = "Annotation",
	sample_1 = "CT26", sample_2 = "CT26_CAF",
	sample_identity = "Sample")

permutation_plot(prop_test) +
  ggtitle("CT26 vs. CT26+CAF")

```

## DEGs

```{r, message = F, warning = F, fig.width = 8, fig.height = 4, eval = F}

#tumor_DEGs <- get_DEGs(seuratdata = seurat_integrated,
#                       celltypes = unique(seurat_integrated$harmony_snn_res.0.8),
#                       groupvar = "PrePost",
#                       group1 = "Treated",
#                       group2 = "Baseline")
tumor_only <- subset(seurat_integrated, subset = harmony_snn_res.0.8 %in% c(0, 2, 4, 7, 18, 21,
                                                                            16, 5, 9, 8, 14, 15, 3,
                                                                            19, 1, 6))

Idents(tumor_only) <- tumor_only$Sample
tumor_DEGs <- FindMarkers(tumor_only,
                          ident.1 = "CT26",
                          ident.2 = "CT26_CAF")

# Distribution of p-values and log2FC
hist(tumor_DEGs$p_val)
hist(tumor_DEGs$p_val_adj)
hist(tumor_DEGs$avg_log2FC)

ensembl <- useMart("ensembl", dataset="mmusculus_gene_ensembl")
geneinfo <- getBM(attributes=c("mgi_symbol", "ensembl_gene_id"), 
      filters = 'mgi_symbol', 
      values = rownames(tumor_DEGs), 
      mart = ensembl)

tumor_DEGs$gene_id <- mapvalues(rownames(tumor_DEGs),
                                   from = geneinfo$mgi_symbol,
                                   to = geneinfo$ensembl_gene_id)

tumor_DEGs_sig <- tumor_DEGs %>%
  filter(p_val_adj < 0.01,
         abs(avg_log2FC) > 2)

rownames(tumor_DEGs_sig)

tumor_DEGs_sig %>%
  filter(avg_log2FC>0) %>% rownames()

tumor_DEGs_sig %>%
  filter(avg_log2FC<0) %>% rownames()

```

## Pathway enrichment

```{r, message = F, warning = F, fig.width = 5, fig.height = 8, eval = F}

tumor_DEGs_up <- tumor_DEGs_sig %>%
  filter(avg_log2FC>0)

gse_res <- enrichGO(rownames(tumor_DEGs_up),
                    ont ="BP", 
                    keyType = "SYMBOL",
                    OrgDb = org.Mm.eg.db,
                    minGSSize = 3, 
                    maxGSSize = 1000, 
                    pvalueCutoff = 0.01, 
                    qvalueCutoff = 1,
                    universe = rownames(tumor_DEGs),
                    pAdjustMethod = "none")

ddp <- dotplot(gse_res, showCategory=10, font.size=10, color="pvalue") +
  theme(legend.text=element_text(size=5),
        legend.position = "top",
        legend.box = "vertical",
        text = element_text(size=6))

dim(gse_res)

ddp

# CSM4

VlnPlot(tumor_only,
        group.by = "Sample",
        features = c("TGFB1", "TGFB2", "TGFB3", "VIM", "CDH2", "FN1", "ACTA2", "MMP2", "MMP3", "MMP9", "SOX10", "FOXC2", "S100A11", "COL1A1", "DSC", "EPCAM", "KRT7", "KRT14", "TJP1"),
        pt.size = 0) &
  theme_bw() &
  NoLegend()

```

