---
title: "Plotting the PIPAC data by patient/group"
author: "heinin"
date: "2025-02-11"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

### Load packages

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(arrow)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(googlesheets4)
  library(workflowr)
  library(patchwork)})

```

### Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/PIPAC_spatial/")
set.seed(9999)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

source("/home/hnatri/PIPAC_spatial/code/PIPAC_colors_themes.R")
source("/home/hnatri/PIPAC_spatial/code/plot_functions.R")

```

### Import data

```{r, message = F, warning = F, fig.width = 8, fig.height = 4}

immune <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/immune_complete_subset_clustered_NC50_NN20_PC20_Seurat_annotated.rds")
nonimmune <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/nonimmune_complete_subset_clustered_NC50_NN20_PC20_Seurat_annotated.rds")

seurat_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/PIPAC_NC50_NN20_PC20_Seurat_annotated_metadata_niches.rds")
seurat_data$Tissue <- as.character(seurat_data$Tissue)
seurat_data$Sample <- as.character(seurat_data$Sample)
seurat_data$Timepoint <- as.character(seurat_data$Timepoint)
seurat_data$Location_Quadrant <- as.character(seurat_data$Location_Quadrant)

```

### Updating some annotations

```{r, message = F, warning = F, fig.width = 8, fig.height = 4, eval = F}

seurat_data$Annotation <- gsub("M4", "Stromal1", seurat_data$Annotation)
seurat_data$Annotation <- gsub("M5", "M4", seurat_data$Annotation)
seurat_data$Annotation <- gsub("M6", "M5", seurat_data$Annotation)
seurat_data$Annotation <- gsub("M7", "M6", seurat_data$Annotation)
seurat_data$Annotation <- gsub("M8", "M7", seurat_data$Annotation)
seurat_data$Annotation <- gsub("M9", "M8", seurat_data$Annotation)
seurat_data$Annotation <- gsub("F5", "Stromal2", seurat_data$Annotation)

saveRDS(seurat_data, "/tgen_labs/banovich/PIPAC/Seurat/PIPAC_NC50_NN20_PC20_Seurat_annotated_metadata_niches.rds")

setdiff(names(pipac_celltype_col), seurat_data$Annotation)
setdiff(seurat_data$Annotation, names(pipac_celltype_col))

#seurat_arm3$Annotation <- gsub("M4", "Stromal1", seurat_arm3$Annotation)
#seurat_arm3$Annotation <- gsub("M5", "M4", seurat_arm3$Annotation)
#seurat_arm3$Annotation <- gsub("F5", "Stromal2", seurat_arm3$Annotation)

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 6}

DimPlot(seurat_data,
        group.by = "Annotation",
        cols = pipac_celltype_col,
        reduction = "umap",
        raster = T,
        label = T,
        repel = T) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  NoLegend() +
  ggtitle("Celltype")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 6, eval = F}

DimPlot(immune,
        group.by = "annot2",
        cols = pipac_celltype_col,
        reduction = "umap",
        raster = T,
        label = T,
        repel = T) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  NoLegend() +
  ggtitle("Celltype")

DimPlot(nonimmune,
        group.by = "annot2",
        cols = pipac_celltype_col,
        reduction = "umap",
        raster = T,
        label = T,
        repel = T) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  NoLegend() +
  ggtitle("Celltype")

rm(immune)
rm(nonimmune)

```

### Plotting by sample

```{r, message = F, warning = F, fig.width = 12, fig.height = 24, eval = T}

sample_dimplots <- lapply(sort(unique(seurat_data$Sample)), function(sample){
  message(sample)
  
  DimPlot(subset(seurat_data, subset = Sample == sample),
        reduction = "sp",
        group.by = "Annotation",
        #split.by = "Sample",
        cols = pipac_celltype_col,
        raster = T,
        pt.size = 3) +
    coord_fixed(ratio = 1) +
    theme_classic() +
    NoLegend() +
    ggtitle(sample)
})

#wrap_plots(sample_dimplots, ncol = 6)

#saveRDS(sample_dimplots, "/scratch/hnatri/PIPAC/sample_dimplots.rds")

```

### Spatial plots by tissue

```{r, message = F, warning = F, fig.width = 8, fig.height = 5, eval = F}

DimPlot(seurat_data,
        group.by = "Tissue",
        cols = tissue_col,
        reduction = "sp_adj",
        raster = T,
        pt.size = 3) +
    coord_fixed(ratio = 1) +
    theme_classic() +
    NoLegend() +
  coord_fixed()

```

### Plotting each sample for each patient

```{r, message = F, warning = F, fig.width = 12, fig.height = 4, eval = T}

patient_dimplots <- lapply(sort(unique(seurat_data$Patient_ID)), function(patient){
  message(patient)
  
  # Finding all samples for the patient
  samples <- seurat_data@meta.data %>%
    filter(Patient_ID == patient) %>%
    dplyr::select("Patient_ID", "Sample", "Tissue", "Timepoint", "Location_Quadrant") %>%
    distinct() %>%
    arrange(Timepoint, Tissue, Location_Quadrant)
  
  patient_dimplots <- lapply(samples$Sample, function(sample){
    titlerow <- samples %>% filter(Sample == sample)
    titlestr <- paste0(unlist(titlerow[c(1, 3, 4, 5)]), collapse = ", ")
    
    DimPlot(subset(seurat_data, subset = Sample == sample),
          reduction = "sp",
          group.by = "Annotation",
          cols = pipac_celltype_col,
          raster = T,
          pt.size = 3,) +
      coord_fixed(ratio = 1) +
      theme_classic() +
      NoLegend() +
      ggtitle(titlestr) +
      plot_theme +
      theme(plot.title = element_text(size=14))
    
  })
})

names(patient_dimplots) <- sort(unique(seurat_data$Patient_ID))

saveRDS(patient_dimplots, "/scratch/hnatri/PIPAC/patient_dimplots.rds")

```

```{r, message = F, warning = F, fig.width = 20, fig.height = 20}

patient_dimplots <- readRDS("/scratch/hnatri/PIPAC/patient_dimplots.rds")

lapply(names(patient_dimplots), function(patient){
  
  wrap_plots(patient_dimplots[[patient]],
             ncol = 4)

})

```

