---
title: "Publication ready plots"
author: "heinin"
date: "2025-12-04"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

## Packages and environment variables

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(arrow)
  library(dplyr)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(googlesheets4)
  library(workflowr)
  library(RColorBrewer)})

```

## Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/PIPAC_spatial/")
set.seed(9999)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

source("/home/hnatri/PIPAC_spatial/code/PIPAC_colors_themes.R")
source("/home/hnatri/PIPAC_spatial/code/plot_functions.R")

# Markers
main_plot_features <- c("PTPRC", "CD3D", "CD3E", "CD4", "CD8A", "JAK1", "JAK2", "STAT4", "STAT3", "TIGIT", "GZMB", "SELL", "CD19", "CD68", "CD44", "MARCO", "APOE", "C1QB", "C1QBP", "CD163", "SPP1", "VCAN", "MUC5AC", "NOTCH3", "RGS5", "MS4A1", "PGA5", "PLVAP", "CCL21", "LYVE", "SPARCL1", "FN1", "DCN", "LUM", "COL1A2", "PDPN", "ACTA2", "LMNA", "EGR3", "TP53", "JUN", "FOS", "BRAF", "KIT", "SOX9", "RNF43", "EPCAM", "PECAM", "CEACAM", "TGFB1", "JUNB", "TCF7", "GZMA", "GZMK", "CD47", "CD74", "LYZ", "TREM2", "CD247", "COL5A1", "SPARC", "CD36", "CTLA4", "RGS1", "CCL2", "SELENOP", "LYVE1", "CTSD", "MMP9", "CDK1", "FLT1", "RAMP2", "CCL14", "MCAM", "NRP1", "CEACAM6", "IL32", "TGFBI", "VEGFA", "LAMP1", "IGFBP7", "POSTN", "C1S", "C1R", "CSF1", "NOTCH1", "FOXP3", "IL2RB", "TUBA1B", "S100A9", "C3", "CXCR2", "SDC1", "CD38", "IGHG1", "PRDX4", "ICAM1", "GATA2", "CXCL3")

mycafs <- c("TGFB1", "ACTA2", "TAGLN") #"HOPX", "MYL9"
icafs <- c("IL6", "CXCL12", "CXCL14") #"CXCL13", 
apcafs <- c("CD74", "HLA-DPB1", "HLA-DPB2", "HLA-DQA1", "HLA-DRA", "HLA-DRB1")
ficafs <- c("SFRP2", "SFRP4", "COMP", "CXCL14", "PLA2G2A", "ASPN")

main_plot_features <- c(main_plot_features, mycafs, icafs, apcafs, ficafs)
main_plot_features <- unique(main_plot_features)

```

## Marker information and metadata

```{r, message = F, warning = F, fig.width = 6, fig.height = 4}

# Cell type markers by group
gs4_deauth()
markers_by_group  <- gs4_get("https://docs.google.com/spreadsheets/d/1w0wrL-5KwNEWi_VpmriN7YmfwpBPlEYX0MKlwI2ZQu8/edit?usp=sharing")
markers_by_group <- read_sheet(markers_by_group, sheet = "Markers by group")

metadata  <- gs4_get("https://docs.google.com/spreadsheets/d/1sXXwOreLxjMSUoPt79c6jmaQpluWkaxA5P5HfDsed3I/edit?usp=sharing")
markers <- read_sheet(metadata, sheet = "Markers")
#final_annotations <- read_sheet(metadata, sheet = "Cell type annotations, all transcripts, final")
final_annotations <- read_sheet(metadata, sheet = "CT update clean")

```

## Import data

```{r, message = F, warning = F, fig.width = 6, fig.height = 6, eval = F}

seurat_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/Freeze/cell_merged_spatial_filtered_splitsamples_clustered_NN30_PC50_Seurat_denoIST_annotated_updated.rds")

unique(seurat_data$Celltype_Updated)
sort(unique(seurat_data$Celltype_Final))

#setdiff(seurat_data$Old_Celltype_Final, final_annotations$Old_Celltype_Final)

#seurat_data$Old_Celltype_Final <- seurat_data$Celltype_Final
#seurat_data$Celltype_Final <- mapvalues(seurat_data$Old_Celltype_Final,
#                                  from = final_annotations$Old_Celltype_Final,
#                                  to = final_annotations$Celltype_Final)
#
#as.data.frame(table(seurat_data$Celltype_Final))

write.table(as.data.frame(table(seurat_data$Celltype_Final)),
            "/home/hnatri/PIPAC_spatial/ncells.tsv",
            quote = F, row.names = F, sep = "\t")

#saveRDS(seurat_data, "/tgen_labs/banovich/PIPAC/Seurat/cell_merged_spatial_filtered_splitsamples_clustered_NN30_PC50_Seurat_denoIST_annotated_updated.rds")

```

```{r, message = F, warning = F, fig.width = 8, fig.height = 10}

seurat_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/Freeze/cell_merged_spatial_filtered_splitsamples_clustered_NN30_PC50_Seurat_denoIST_annotated_updated.rds")

sort(unique(seurat_data$Celltype_Final))

DefaultAssay(seurat_data) <- "RNA"
seurat_data <- NormalizeData(seurat_data)
seurat_data <- ScaleData(seurat_data)

DefaultAssay(seurat_data) <- "denoist_RNA"
seurat_data <- NormalizeData(seurat_data)
seurat_data <- ScaleData(seurat_data)

```

## Plotting annotations

```{r, message = F, warning = F, fig.width = 8, fig.height = 10}


celltype_final <- as.factor(sort(unique(seurat_data$Celltype_Final)))
celltype_final_col <- colorRampPalette(brewer.pal(10, "Paired"))(nb.cols <- length(celltype_final))
names(celltype_final_col) <- levels(celltype_final)

DimPlot(seurat_data,
        group.by = "Celltype_Final",
        cols = celltype_final_col,
        reduction = "umap",
        raster = T,
        label = T,
        label.box = T) +
  coord_fixed(ratio = 1) +
  theme_classic() +
  NoLegend()

```

## Plotting top markers and canonical markers

```{r, message = F, warning = F, fig.width = 18, fig.height = 40}

markers <- presto::wilcoxauc(seurat_data,
                             group_by = "Celltype_Final",
                             assay = "data",
                             seurat_assay = "RNA")
top_markers <- markers %>% group_by(group) %>% slice_max(order_by = auc, n = 50)

write.table(top_markers, "/home/hnatri/PIPAC_spatial/cell_annotation_final_topmarkers.tsv",
            sep = "\t", quote = F, row.names = T)

hp <- create_dotplot_heatmap(seurat_object = seurat_data,
                             plot_features = unique(c(top_markers$feature, main_plot_features)),
                             group_var = "Celltype_Final",
                             group_colors = celltype_final_col,
                             column_title = "",
                             row_km = 12,
                             col_km = 12,
                             row.order = NULL,
                             col.order = NULL)

```

## Annotation groups

```{r, message = F, warning = F, fig.width = 16, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "Cell-cell crosstalk"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Cell-cell crosstalk")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "Macrophage signaling"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Macrophage signaling")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "DNA damage and cell faith"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("DNA damage and cell faith")

```

```{r, message = F, warning = F, fig.width = 10, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "Functional markers"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Functional markers")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "Mesothelial"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Mesothelial")

```

```{r, message = F, warning = F, fig.width = 10, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "Macrophages"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Macrophages")

```

```{r, message = F, warning = F, fig.width = 10, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = unique(markers_by_group[which(markers_by_group$annotation1 == "CAFs"),]$feature),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("CAFs")

```

```{r, message = F, warning = F, fig.width = 6, fig.height = 15, eval = T}

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = grep("COL", rownames(seurat_data), value = T),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("Collagen")

```

### Cell cycle markers

```{r, message = F, warning = F, fig.width = 6, fig.height = 15, eval = T}

s.genes <- cc.genes.updated.2019$s.genes
g2m.genes <- cc.genes.updated.2019$g2m.genes

DotPlot(seurat_data,
        group.by = "Celltype_Final",
        features = c(s.genes, g2m.genes),
        cols = c("gray89", "tomato3")) +
  RotatedAxis() +
  ggtitle("S/G2M genes")

```

## Plotting selected informative markers

```{r, message = F, warning = F, fig.width = 15, fig.height = 17}

selected_markers <- c("CCL21", "SPP1", "CD3E", "IL7R", "CD47", "JCHAIN",
                      "IGHG1", "CXCL10", "CXCL9", "ENTPD1", "NOTCH3", "PTEN",
                      "LYVE1", "S100A8", "LYZ", "VSIR", "ACTB", "CD28", "CD274",
                      "C1QC", "C1QB", "CD163", "LGMN", "EPCAM",
                      "CEACAM6", "VIM", "PDPN", "COL1A2", "COL5A1", "ACTA2",
                      "CCL21", "RGS5", "SELL", "CD8A", "CD4", "FN1",
                      "FOXP3", "TIGIT", "STAT3", "MSLN", "LRRN4", "MARCO",
                      "FAP", "POSTN", "MKI67", "CD248", "UBE2C", "HSPH1",
                      "SELENOP", "S100A9", "SLC40A1", "TGFBI", "APOE", "CD9",
                      "DDR1", "HAVCR2", "CTLA4", "TSPAN1", "CDKN1A", "CCNE2",
                      "SIRPA", "PTPN6", "SIGLEC10", "TNFRSF14", "ITGAV",
                      "VEGFA", "NRP1", "CD36", "C1R", "CD14", "CD27", "IGKC",
                      "BANK1", "NOTCH2", "JAK2", "FLT1", "IL7R", "DGKA",
                      "CXCR4", "KLRK1", "XBP1")

selected_markers <- c(selected_markers, mycafs, icafs, apcafs, ficafs)
selected_markers <- unique(selected_markers)

selected_markers <- setdiff(selected_markers, c("IL6"))

DefaultAssay(seurat_data) <- "RNA"
hp <- create_dotplot_heatmap(seurat_object = seurat_data,
                             plot_features = selected_markers,
                             group_var = "Celltype_Final",
                             group_colors = celltype_final_col,
                             column_title = "",
                             row_km = 10,
                             col_km = 6,
                             row.order = NULL,
                             col.order = NULL)

DefaultAssay(seurat_data) <- "denoist_RNA"
hp <- create_dotplot_heatmap(seurat_object = seurat_data,
                             plot_features = selected_markers,
                             group_var = "Celltype_Final",
                             group_colors = celltype_final_col,
                             column_title = "",
                             row_km = 10,
                             col_km = 6,
                             row.order = NULL,
                             col.order = NULL)

```

## QC metrics by cell type

```{r, message = F, warning = F, fig.width = 22, fig.height = 30, eval = T}

VlnPlot(seurat_data,
        features = c("nCount_RNA", "nCount_cell_RNA", "nFeature_RNA",
                     "nFeature_cell_RNA", "transcript_counts", "cell_area",
                     "nucleus_area", "nucleus_count"),
        group.by = "Celltype_Final",
        pt.size = 0,
        ncol = 1,
        cols = celltype_final_col) &
  theme_minimal() &
  RotatedAxis() &
  NoLegend()

```

## Numbers of cells per celltype

```{r, message = F, warning = F, fig.width = 16, fig.height = 3}

ct_table <- as.data.frame(table(seurat_data$Celltype_Final))
colnames(ct_table) <- c("Celltype_Final", "Freq")

min(ct_table$Freq)

ggplot(ct_table, aes(x = reorder(Celltype_Final, -Freq), y = Freq, fill = Celltype_Final)) +
       geom_bar(stat="identity", position='stack', width = 0.8) +
       scale_fill_manual(name = "Celltype_Final", values = celltype_final_col) +
       xlab("") +
       ylab("Cell count") +
       theme_classic() +
       theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) +
       NoLegend()

```


```{r, message = F, warning = F, fig.width = 10, fig.height = 20, eval = T}


# Rscript -e "rmarkdown::render('pretty_plots.Rmd')"

```

