---
title: "Proximity analysis on PIPAC Xenium data"
author: "heinin"
date: "2025-09-19"
output:
  workflowr::wflow_html:
    code_folding: hide
  html_notebook: default
editor_options:
  chunk_output_type: console
---

### Load packages

```{r, warning=F, message=F}

suppressPackageStartupMessages({
  library(workflowr)
  library(Seurat)
  library(SeuratObject)
  library(SeuratDisk)
  library(tidyverse)
  library(tibble)
  library(ggplot2)
  library(ggpubr)
  library(ggrepel)
  library(googlesheets4)
  library(workflowr)
  library(patchwork)
  library(spatstat)})

```

### Environment variables and helper functions

```{r, message = F, warning = F}

setwd("/home/hnatri/PIPAC_spatial/")
set.seed(9999)
options(future.globals.maxSize = 30000 * 1024^2)
options(scipen = 99999)
options(ggrepel.max.overlaps = Inf)

source("/home/hnatri/PIPAC_spatial/code/PIPAC_colors_themes.R")
source("/home/hnatri/PIPAC_spatial/code/plot_functions.R")

calc_enrichment <- function(summary_table, anchor_celltype){
  enrich_score_ct <- c()
  for(j in 1:nrow(summary_table)){
    
    ct <- summary_table[j, 1] %>% unlist() %>% unname() %>% as.character()
    total <- summary_table[j, 4] %>% unlist() %>% unname()
    list1 <- summary_table[j, 2] %>% unlist() %>% unname()
    list2 <- summary_table[j, 5] %>% unlist() %>% unname()
    overlap <- summary_table[j, 3] %>% unlist() %>% unname()
    res <- fisher.test(matrix(c((total - (list1 + list2) + overlap),  (list1-overlap),  (list2 - overlap), overlap), nrow=2))
    
    tmp0 <- data.frame(prox_to = anchor_celltype, prox_ct = ct, 
                       pval = res$p.value, or = res$estimate, or05 = res$conf.int[1], or95 = res$conf.int[2])
    enrich_score_ct <- rbind(enrich_score_ct, tmp0)
  }
  enrich_score_ct <- within(enrich_score_ct, {
    log_or = log(or)
    log_or05 = log(or05)
    log_or95 = log(or95)
  })
  enrich_score_ct$prox_ct <- factor(enrich_score_ct$prox_ct, levels = as.character(enrich_score_ct[order(enrich_score_ct$or, decreasing = F),]$prox_ct))
  return(enrich_score_ct)
}

```

### Import data

```{r, message = F, warning = F, fig.width = 8, fig.height = 4}

#seurat_data <- readRDS("/tgen_labs/banovich/PIPAC/Seurat/cell_merged_spatial_filtered_splitsamples_clustered_NC50_NN20_PC20_Seurat_denoIST_metadata_ncells3k_nk20_niches.rds")

```

### Calculating enrichment

```{r, message = F, warning = F, fig.width = 8, fig.height = 4, eval = F}


```


